name: Path Tracer
on:
  push:
  workflow_dispatch:

jobs:
  trace-path:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This gives the bot permission to create path.txt
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find and Record
        run: |
          # Search for the files and append their paths to path.txt
          # We use 'sed' to clean up the './' from the start
          find . -name "librebox.js" | sed 's|^\./||' >> path.txt
          find . -name "librebox.wasm" | sed 's|^\./||' >> path.txt

      - name: Commit Path File
        run: |
          git config --global user.name "Ramcycle-Bot"
          git config --global user.email "bot@ramcycle.com"
          git add path.txt
          # The '|| true' stops it from crashing if the path hasn't changed
          git commit -m "Update path.txt with found locations" || true
          git push
