name: Scout
on:
  push:
  workflow_dispatch:

jobs:
  find-it:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Search and Report
        run: |
          echo "HUNTING FOR THE GOODS..."
          # This find command will print the exact path starting from ./
          # If it finds nothing, it stays silent.
          find . -name "librebox.js" -print
          find . -name "librebox.wasm" -print
          echo "SEARCH COMPLETE."
